# Generated by Django 4.1.4 on 2023-02-14 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DimComponentType",
            fields=[
                ("type_id", models.AutoField(primary_key=True, serialize=False)),
                ("type_code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MapComponent",
            fields=[
                ("component_id", models.AutoField(primary_key=True, serialize=False)),
                ("ext_device_id", models.IntegerField()),
                (
                    "type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records_manager.dimcomponenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("ext_device_id", "type_id")},
            },
        ),
        migrations.CreateModel(
            name="FctRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                ("datetime", models.DateTimeField()),
                ("value", models.FloatField()),
                (
                    "component_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records_manager.mapcomponent",
                    ),
                ),
            ],
        ),
    ]
